Feat/water 2864 streaming
DEFRA/water-abstraction-reporting pull request #4
Opened 2021-04-08 12:21 UTC by timtamimi

2021-04-14 08:39 UTC, james-siteclick requested changes

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/helpers/financial-year.js
> +const getFinancialYear = (date = new Date()) => {
An library implementation for this is already available here:
```
const { getFinancialYear } = require('@envage/water-abstraction-helpers').charging;
```

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/helpers/write-csv-to-s3.js
> +    fs.readFile(filePath, 'utf-8', (err, data) => {
Is the intermediate flat file needed?
Not sure how large the reports are, but if they are large there could be a risk it will exceed the disk space on the box.
Also if we are using one it should be deleted after processing.

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/message-queue-v2.js
> +'use strict';
If the `QueueManager` class and/or plugin is copied and pasted from the water service we should prob move it to the helpers library.

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/queries/billedActiveLicences.js
> +left join water.licence_agreements la on
If we are left joining on financial agreements we may will get duplicate rows (if a licence has 2+ agreements) - does this matter?

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/queries/unbilledActiveLicences.js
> +left join water.licence_agreements la on
As above, not sure if it is important this could lead to mostly duplicate rows

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/queries/uncreditedInactiveLicences.js
> +left join water.licence_agreements la on
Same again

2021-04-14 08:39 UTC, james-siteclick commented on src/lib/reports-handlers/uncreditedInactiveLicencesReportHandler.js
> +const handler = async () => {
As far as I can tell these 3 report handlers look nearly identical and could be refactored

2021-04-14 08:39 UTC, james-siteclick commented on src/reports-generator.js
> +          repeat: {
I'm guessing maybe the use of Bull MQ repeat is the reason for needing to clear the Redis queue above when the service starts?

Another option, assuming the report needs to run e.g. nightly, would be to use node-cron to publish the job with a job ID that includes the current date.

2021-04-16 08:08 UTC, timtamimi commented on src/lib/helpers/financial-year.js
> +const getFinancialYear = (date = new Date()) => {
Aha! Thank you :D I was unaware of this. That's helpful.

2021-04-19 08:12 UTC, timtamimi commented on src/lib/helpers/write-csv-to-s3.js
> +    fs.readFile(filePath, 'utf-8', (err, data) => {
Fair - So, the reports vary in size (anything from a few KB to 50MB) but they were set to over-write pre-existing copies, so theoretically it should never cause an enormous storage build-up. 

In any case, a deletion step will be added shortly as suggested to keep it tidy. :)

2021-04-19 08:14 UTC, timtamimi commented on src/lib/message-queue-v2.js
> +'use strict';
Totally agree, and in all likelihood this will be copied to other modules in due course I imagine, so yes we should abstract is and whack it in helpers and then go back and edit the water service to consume the shared class instead of creating its own. Leaving it for **_now_** though.

2021-04-19 08:16 UTC, timtamimi commented on src/lib/reports-handlers/uncreditedInactiveLicencesReportHandler.js
> +const handler = async () => {
You're right. I'll refactor this.

2021-04-19 08:18 UTC, timtamimi commented on src/reports-generator.js
> +          repeat: {
That's right - If/when the service restarts, I'm currently asking it to clear the queue to avoid creating duplicates of the same job.

This simplistic approach is OK for now as all the reports are generating at the same frequency. If (or when) we have reports that need to generate more or less frequently, we'll indeed be better off publishing jobs with specific timestamps, but I don't _**think**_ this is necessary at the moment.

2021-04-19 11:44 UTC, timtamimi commented on src/lib/queries/billedActiveLicences.js
> +left join water.licence_agreements la on
Good point. I wondered the same myself. Having spoken to Russell, we think this is OK/as intended. :)

2021-04-19 11:44 UTC, timtamimi commented on src/lib/queries/unbilledActiveLicences.js
> +left join water.licence_agreements la on
As above: Good point. I wondered the same myself. Having spoken to Russell, we think this is OK/as intended. :)

2021-04-19 11:44 UTC, timtamimi commented on src/lib/queries/uncreditedInactiveLicences.js
> +left join water.licence_agreements la on
As above: Good point. I wondered the same myself. Having spoken to Russell, we think this is OK/as intended. :)

2021-04-22 15:55 UTC, james-siteclick requested changes
Not for this PR necessarily but just a note - for functions with a Node callback style API it's quite nice to do, e.g.:
```
const readFile = require('util').promisify(fs.readFile);
```

Then you can use async/await which avoids the nested callbacks:
```
const data = await readFile(filePath);
```

2021-04-22 15:55 UTC, james-siteclick commented on test/lib/helpers/report-handler.js
> +    await sandbox.stub(pool, 'query').resolves({ rows: [], fields: [] });
Don't think any of these need `await`

2021-04-22 15:55 UTC, james-siteclick commented on test/lib/helpers/report-handler.js
> +      await handler();
I think only this line needs the `await`

2021-04-22 15:58 UTC, james-siteclick requested changes

2021-04-22 15:58 UTC, james-siteclick commented on src/lib/helpers/write-csv-to-s3.js
> +          throw s3Err;
I think (although not certain) that if any of these errors are thrown they will be unhandled errors because they occur in a callback. 

There's a chance this could possibly bubble up and crash the application.  

I'd suggest this function might need to return a promise, which could probably be done most easily with the require('util').promisify thing

2021-04-22 17:18 UTC, timtamimi commented on test/lib/helpers/report-handler.js
> +    await sandbox.stub(pool, 'query').resolves({ rows: [], fields: [] });
I've removed the unnecessary awaits in 8b2b0e4

2021-04-22 17:18 UTC, timtamimi commented on test/lib/helpers/report-handler.js
> +      await handler();
I've removed the unnecessary awaits in 8b2b0e4

2021-04-26 11:57 UTC, timtamimi commented on src/lib/helpers/write-csv-to-s3.js
> +          throw s3Err;
Addressing this in e853005

2021-04-26 12:30 UTC, james-siteclick approved these changes

2021-04-26 15:01 UTC, merged